### ISSUE TITLE
Text in comment box should be lighter

### ISSUE THREAD

**Issue by awebeer256** [JazzJames/WebtoonDark#2]
This userstyle sets the comment box background to `#2A2A2A`, while the text colour in the same place remains the site default of `#333`:
![image](https://user-images.githubusercontent.com/26385859/120938470-dc8af400-c6e0-11eb-87f9-827502d416e8.png)
This is really hard to see:
![image](https://user-images.githubusercontent.com/26385859/120938515-152acd80-c6e1-11eb-962e-b32a21801e77.png)
I suggest setting text to `--lgray`:
![image](https://user-images.githubusercontent.com/26385859/120938592-6dfa6600-c6e1-11eb-85c6-fb8dfb40daa4.png)

**Comment by JazzJames** [comment]
Thank you!
Implemented in v1.0.9
